
/**
 * The class RandomNumber is used to generate random number using and importing Random class.
 * The random number will be generated between 1 to 100.
 * There are also  get methods which are used for accessing the variable generated by getHiddenNumber Method
 * There are also  get methods which are used for accessing the variable generated by getChancePlayer Method
 * There are also  get methods which are used for accessing the variable generated by getRandomNumberGenerator Method
 * @author   Kanishka Mehrotra
 * @version  V1.0 20th April 2018
 */
import java.util.Random;

public class RandomNumber
{
    private int lowerLimit ;
    private int upperLimit;
    private int hiddenNumber;
    private int limitSet;
      /**
     * The getChancePlayer method just uses Random class function by just importing it in this method to decide the turn for computer or player
     * The method generates random no between 1 to 100
     * @return    turnDecision generates the random number between 0 to 1
     */
 
    public int getChancePlayer()

    {
        Random decideTurn = new Random();
        int turnDecision = decideTurn.nextInt(1);
        return turnDecision;
    }
    
     /**
     * The getHiddenNumber method just uses Random class function by just importing it in this method
     * The method generates random no between 1 to 100
     * @return    hiddenNumber generates the random number between 1 to 100
     */
    public int getHiddenNumber()
    {
        Random hidNo = new Random();
        int hiddenNumber = hidNo.nextInt(3) + 1;
        return hiddenNumber;
    }
    
    /**
     * Constructor for objects of class RandomNumber
     * randomNo is initialize to 0
     */
    
    public RandomNumber()
    {
        hiddenNumber = 0;
        lowerLimit = 0;
        upperLimit = 0;
    }
    
    /**
     * The getRandomNumberGenerator method just uses Random class function by just importing it in this method
     * The method generates random no between lower limit and upper limit
     * @return    limitSet returns the lower and upper limit the random number between 1 to 5
     */
    
    public int getRandomNumberGenerator(int lowerLimit,int upperLimit)
    {
        Random randNum = new Random();
        int limitSet = lowerLimit + randNum.nextInt((upperLimit - lowerLimit) + 1);
        return limitSet;
    }
   
    
}
